// Demo data for DealGate by Hummingbird

export const INSTITUTION_TYPES = {
  bank: { label: 'Bank', color: '#04433D', bg: '#e8f5f0', border: '#CAE3DA', icon: 'Landmark' },
  credit_union: { label: 'Credit Union', color: '#4C9E82', bg: '#e8f5f0', border: '#CAE3DA', icon: 'Users' },
  insurance: { label: 'Insurance', color: '#3985BE', bg: '#e8f4fc', border: '#b3d4ec', icon: 'Shield' },
  asset_manager: { label: 'Asset Manager', color: '#1B4332', bg: '#e8f5f0', border: '#CAE3DA', icon: 'TrendingUp' },
  fintech: { label: 'Fintech', color: '#4C9E82', bg: '#e8f5f0', border: '#a3d4c0', icon: 'Zap' },
};

export const SALES_STAGES = [
  'Prospecting', 'Discovery', 'Technical Eval', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost'
];

export const PROCUREMENT_STAGES = [
  'Not Started', 'Vendor Registration', 'Security Questionnaire', 'Risk Assessment',
  'Compliance Review', 'Legal Review', 'Approval Chain', 'Approved'
];

export const TEAM = [
  { id: '1', name: 'Hannah Park', role: 'Account Executive', avatar: 'HP' },
  { id: '2', name: 'Victor Chen', role: 'VP Sales', avatar: 'VC' },
  { id: '3', name: 'Olivia Scott', role: 'Account Executive', avatar: 'OS' },
  { id: '4', name: 'James Morrison', role: 'Account Executive', avatar: 'JM' },
  { id: '5', name: 'Maya Lindgren', role: 'RevOps Manager', avatar: 'ML' },
];

export const DEALS = [
  {
    id: '1',
    name: 'AML Investigation Platform',
    institution: 'Grasshopper Bank',
    type: 'bank',
    value: 285000,
    salesStage: 'Negotiation',
    salesStageIndex: 4,
    procurementStage: 'Risk Assessment',
    procurementStageIndex: 3,
    procurementDays: 45,
    docCompletion: 67,
    daysInStage: 18,
    owner: TEAM[0],
    closeDate: '2025-04-15',
    adjCloseDate: '2025-05-28',
    riskLevel: 'medium',
    approvalSteps: [
      { title: 'IT Security', status: 'approved' },
      { title: 'BSA/AML Compliance', status: 'approved' },
      { title: 'Risk Committee', status: 'in_review' },
      { title: 'Legal', status: 'pending' },
      { title: 'CFO', status: 'pending' },
      { title: 'Board', status: 'pending' },
    ],
    documents: [
      { name: 'Security Questionnaire', status: 'in_review', progress: 80, reviewer: 'IT Security Team', due: '2025-02-01' },
      { name: 'SOC 2 Type II Report', status: 'submitted', reviewer: 'BSA/AML Compliance', due: null },
      { name: 'Data Processing Agreement', status: 'draft', reviewer: 'Legal', due: '2025-02-15' },
      { name: 'Vendor Risk Assessment', status: 'pending', reviewer: 'Risk Committee', due: '2025-03-01' },
      { name: 'System Architecture Diagram', status: 'approved', reviewer: 'CTO Office', due: null },
      { name: 'Penetration Test Report', status: 'approved', reviewer: 'Security', due: null },
    ],
  },
  {
    id: '2',
    name: 'SAR Filing Automation',
    institution: 'BHG Financial',
    type: 'bank',
    value: 195000,
    salesStage: 'Proposal',
    salesStageIndex: 3,
    procurementStage: 'Security Questionnaire',
    procurementStageIndex: 2,
    procurementDays: 22,
    docCompletion: 45,
    daysInStage: 12,
    owner: TEAM[2],
    closeDate: '2025-03-30',
    adjCloseDate: '2025-05-10',
    riskLevel: 'low',
    approvalSteps: [
      { title: 'IT Security', status: 'in_review' },
      { title: 'BSA Officer', status: 'pending' },
      { title: 'Legal', status: 'pending' },
      { title: 'CIO', status: 'pending' },
    ],
    documents: [
      { name: 'Security Questionnaire', status: 'in_review', progress: 60, reviewer: 'IT Security', due: '2025-02-20' },
      { name: 'SOC 2 Type II Report', status: 'submitted', reviewer: 'BSA/AML Compliance', due: null },
      { name: 'FinCEN Compliance Documentation', status: 'submitted', reviewer: 'BSA Officer', due: null },
    ],
  },
  {
    id: '3',
    name: 'Customer Screening Module',
    institution: 'Navy Federal Credit Union',
    type: 'credit_union',
    value: 98000,
    salesStage: 'Negotiation',
    salesStageIndex: 4,
    procurementStage: 'Legal Review',
    procurementStageIndex: 5,
    procurementDays: 8,
    docCompletion: 90,
    daysInStage: 5,
    owner: TEAM[0],
    closeDate: '2025-02-28',
    adjCloseDate: '2025-03-10',
    riskLevel: 'low',
    approvalSteps: [
      { title: 'IT Security', status: 'approved' },
      { title: 'BSA/AML Compliance', status: 'approved' },
      { title: 'Legal', status: 'in_review' },
      { title: 'Board', status: 'pending' },
    ],
    documents: [
      { name: 'Security Questionnaire', status: 'approved', reviewer: 'IT Security', due: null },
      { name: 'SOC 2 Type II Report', status: 'approved', reviewer: 'Compliance', due: null },
      { name: 'Data Processing Agreement', status: 'in_review', reviewer: 'Legal', due: '2025-02-20' },
      { name: 'Vendor Risk Assessment', status: 'approved', reviewer: 'Risk', due: null },
    ],
  },
  {
    id: '4',
    name: 'Transaction Monitoring Suite',
    institution: 'Raymond James',
    type: 'asset_manager',
    value: 320000,
    salesStage: 'Technical Eval',
    salesStageIndex: 2,
    procurementStage: 'Not Started',
    procurementStageIndex: 0,
    procurementDays: 0,
    docCompletion: 0,
    daysInStage: 8,
    owner: TEAM[3],
    closeDate: '2025-05-15',
    adjCloseDate: '2025-07-15',
    riskLevel: 'medium',
    approvalSteps: [],
    documents: [],
  },
  {
    id: '5',
    name: 'KYC/CDD Onboarding',
    institution: 'Mercury',
    type: 'fintech',
    value: 52000,
    salesStage: 'Closed Won',
    salesStageIndex: 5,
    procurementStage: 'Approved',
    procurementStageIndex: 7,
    procurementDays: 18,
    docCompletion: 100,
    daysInStage: 0,
    owner: TEAM[2],
    closeDate: '2025-01-15',
    adjCloseDate: '2025-01-15',
    riskLevel: 'low',
    approvalSteps: [
      { title: 'CTO', status: 'approved' },
      { title: 'Legal', status: 'approved' },
    ],
    documents: [
      { name: 'Security Questionnaire', status: 'approved', reviewer: 'CTO', due: null },
      { name: 'Data Processing Agreement', status: 'approved', reviewer: 'Legal', due: null },
    ],
  },
  {
    id: '6',
    name: 'Case Management Platform',
    institution: 'Goldman Sachs',
    type: 'bank',
    value: 410000,
    salesStage: 'Proposal',
    salesStageIndex: 3,
    procurementStage: 'Vendor Registration',
    procurementStageIndex: 1,
    procurementDays: 12,
    docCompletion: 20,
    daysInStage: 22,
    owner: TEAM[1],
    closeDate: '2025-04-30',
    adjCloseDate: '2025-07-01',
    riskLevel: 'high',
    approvalSteps: [
      { title: 'IT Security', status: 'pending' },
      { title: 'BSA/AML Compliance', status: 'pending' },
      { title: 'Risk Committee', status: 'pending' },
      { title: 'Legal', status: 'pending' },
      { title: 'CFO', status: 'pending' },
      { title: 'Board', status: 'pending' },
    ],
    documents: [
      { name: 'Vendor Registration Form', status: 'in_review', progress: 100, reviewer: 'Procurement', due: '2025-02-10' },
      { name: 'Security Questionnaire', status: 'draft', progress: 30, reviewer: 'IT Security', due: '2025-03-01' },
    ],
  },
  {
    id: '7',
    name: 'Risk Monitoring Dashboard',
    institution: 'Nationwide Insurance',
    type: 'insurance',
    value: 175000,
    salesStage: 'Discovery',
    salesStageIndex: 1,
    procurementStage: 'Not Started',
    procurementStageIndex: 0,
    procurementDays: 0,
    docCompletion: 0,
    daysInStage: 6,
    owner: TEAM[3],
    closeDate: '2025-06-30',
    adjCloseDate: '2025-08-30',
    riskLevel: 'low',
    approvalSteps: [],
    documents: [],
  },
  {
    id: '8',
    name: 'AML Transaction Monitoring',
    institution: 'Charles Schwab',
    type: 'asset_manager',
    value: 245000,
    salesStage: 'Negotiation',
    salesStageIndex: 4,
    procurementStage: 'Compliance Review',
    procurementStageIndex: 4,
    procurementDays: 38,
    docCompletion: 78,
    daysInStage: 14,
    owner: TEAM[0],
    closeDate: '2025-03-15',
    adjCloseDate: '2025-04-05',
    riskLevel: 'low',
    approvalSteps: [
      { title: 'IT Security', status: 'approved' },
      { title: 'BSA/AML Compliance', status: 'in_review' },
      { title: 'Legal', status: 'pending' },
      { title: 'COO', status: 'pending' },
    ],
    documents: [
      { name: 'Security Questionnaire', status: 'approved', reviewer: 'IT', due: null },
      { name: 'SOC 2 Type II Report', status: 'approved', reviewer: 'Compliance', due: null },
      { name: 'Vendor Risk Assessment', status: 'in_review', reviewer: 'Risk', due: '2025-02-25' },
      { name: 'Data Processing Agreement', status: 'draft', reviewer: 'Legal', due: '2025-03-05' },
    ],
  },
  {
    id: '9',
    name: 'SAR Filing Workflow',
    institution: 'Stripe',
    type: 'fintech',
    value: 88000,
    salesStage: 'Technical Eval',
    salesStageIndex: 2,
    procurementStage: 'Not Started',
    procurementStageIndex: 0,
    procurementDays: 0,
    docCompletion: 0,
    daysInStage: 4,
    owner: TEAM[2],
    closeDate: '2025-03-20',
    adjCloseDate: '2025-04-05',
    riskLevel: 'low',
    approvalSteps: [],
    documents: [],
  },
  {
    id: '10',
    name: 'Sanctions Screening Platform',
    institution: 'Wells Fargo',
    type: 'bank',
    value: 350000,
    salesStage: 'Proposal',
    salesStageIndex: 3,
    procurementStage: 'Security Questionnaire',
    procurementStageIndex: 2,
    procurementDays: 30,
    docCompletion: 55,
    daysInStage: 16,
    owner: TEAM[1],
    closeDate: '2025-05-01',
    adjCloseDate: '2025-06-20',
    riskLevel: 'medium',
    approvalSteps: [
      { title: 'IT Security', status: 'in_review' },
      { title: 'BSA/AML Compliance', status: 'pending' },
      { title: 'Risk Committee', status: 'pending' },
      { title: 'Legal', status: 'pending' },
      { title: 'CFO', status: 'pending' },
    ],
    documents: [
      { name: 'Security Questionnaire', status: 'in_review', progress: 65, reviewer: 'IT Security', due: '2025-02-28' },
      { name: 'SOC 2 Type II Report', status: 'submitted', reviewer: 'BSA/AML Compliance', due: null },
      { name: 'System Architecture Diagram', status: 'submitted', reviewer: 'CTO', due: null },
    ],
  },
  {
    id: '11',
    name: 'BSA Compliance Automation',
    institution: 'PenFed Credit Union',
    type: 'credit_union',
    value: 76000,
    salesStage: 'Prospecting',
    salesStageIndex: 0,
    procurementStage: 'Not Started',
    procurementStageIndex: 0,
    procurementDays: 0,
    docCompletion: 0,
    daysInStage: 3,
    owner: TEAM[3],
    closeDate: '2025-07-01',
    adjCloseDate: '2025-08-01',
    riskLevel: 'low',
    approvalSteps: [],
    documents: [],
  },
  {
    id: '12',
    name: 'Enterprise AML Suite',
    institution: 'Citi',
    type: 'bank',
    value: 450000,
    salesStage: 'Closed Lost',
    salesStageIndex: 6,
    procurementStage: 'Risk Assessment',
    procurementStageIndex: 3,
    procurementDays: 62,
    docCompletion: 50,
    daysInStage: 0,
    owner: TEAM[0],
    closeDate: '2024-12-15',
    adjCloseDate: '2025-02-15',
    riskLevel: 'high',
    lostReason: 'Procurement stalled — risk committee delayed 3 months',
    approvalSteps: [
      { title: 'IT Security', status: 'approved' },
      { title: 'BSA/AML Compliance', status: 'approved' },
      { title: 'Risk Committee', status: 'rejected' },
    ],
    documents: [],
  },
  {
    id: '13',
    name: 'Case Management & Reporting',
    institution: 'Fidelity Investments',
    type: 'asset_manager',
    value: 210000,
    salesStage: 'Closed Won',
    salesStageIndex: 5,
    procurementStage: 'Approved',
    procurementStageIndex: 7,
    procurementDays: 42,
    docCompletion: 100,
    daysInStage: 0,
    owner: TEAM[1],
    closeDate: '2025-01-10',
    adjCloseDate: '2025-01-10',
    riskLevel: 'low',
    approvalSteps: [
      { title: 'IT Security', status: 'approved' },
      { title: 'BSA/AML Compliance', status: 'approved' },
      { title: 'Legal', status: 'approved' },
      { title: 'CIO', status: 'approved' },
    ],
    documents: [],
  },
  {
    id: '14',
    name: 'Customer Due Diligence',
    institution: 'Allstate',
    type: 'insurance',
    value: 140000,
    salesStage: 'Discovery',
    salesStageIndex: 1,
    procurementStage: 'Not Started',
    procurementStageIndex: 0,
    procurementDays: 0,
    docCompletion: 0,
    daysInStage: 10,
    owner: TEAM[2],
    closeDate: '2025-06-15',
    adjCloseDate: '2025-08-15',
    riskLevel: 'medium',
    approvalSteps: [],
    documents: [],
  },
  {
    id: '15',
    name: 'Regulatory Change Management',
    institution: 'Bank of America',
    type: 'bank',
    value: 395000,
    salesStage: 'Technical Eval',
    salesStageIndex: 2,
    procurementStage: 'Not Started',
    procurementStageIndex: 0,
    procurementDays: 0,
    docCompletion: 0,
    daysInStage: 7,
    owner: TEAM[1],
    closeDate: '2025-06-01',
    adjCloseDate: '2025-08-15',
    riskLevel: 'high',
    approvalSteps: [],
    documents: [],
  },
];

export const BENCHMARKS = [
  { type: 'bank', label: 'Banks', avgDays: 78, docs: '8-12', bottleneck: 'Risk Committee (quarterly meetings)', winRate: 62, tip: 'Start vendor registration early — takes 2+ weeks at major banks' },
  { type: 'credit_union', label: 'Credit Unions', avgDays: 31, docs: '4-6', bottleneck: 'Board approval schedule', winRate: 78, tip: 'Align with board meeting dates — typically monthly' },
  { type: 'insurance', label: 'Insurance', avgDays: 52, docs: '6-8', bottleneck: 'Compliance review backlog', winRate: 65, tip: 'Engage compliance team directly during technical eval' },
  { type: 'asset_manager', label: 'Asset Managers', avgDays: 45, docs: '5-7', bottleneck: 'IT security deep-dive', winRate: 71, tip: 'Share SOC 2 report proactively to speed IT review' },
  { type: 'fintech', label: 'Fintech', avgDays: 18, docs: '2-4', bottleneck: 'Legal (fast but thorough)', winRate: 85, tip: 'Move fast — fintechs expect modern vendor processes' },
];

export const MONTHLY_FORECAST = [
  { month: 'Jan', sales: 262000, adjusted: 52000, closed: 262000 },
  { month: 'Feb', sales: 98000, adjusted: 98000, closed: 0 },
  { month: 'Mar', sales: 580000, adjusted: 345000, closed: 0 },
  { month: 'Apr', sales: 695000, adjusted: 285000, closed: 0 },
  { month: 'May', sales: 545000, adjusted: 545000, closed: 0 },
  { month: 'Jun', sales: 315000, adjusted: 140000, closed: 0 },
];

export const BOTTLENECK_DATA = [
  { stage: 'Vendor Registration', avgDays: 12, color: '#4C9E82' },
  { stage: 'Security Questionnaire', avgDays: 18, color: '#3985BE' },
  { stage: 'Risk Assessment', avgDays: 24, color: '#ef4444' },
  { stage: 'Compliance Review', avgDays: 14, color: '#04433D' },
  { stage: 'Legal Review', avgDays: 10, color: '#1B4332' },
  { stage: 'Approval Chain', avgDays: 8, color: '#6b7280' },
];
